
export const state = {
    user: null, 
    accessToken: null,
    loadingStatus: 'Initialisation...',
    adminIds: [],
    erlcKey: null,
    devKey: null,
    gouvBank: 0,
    lastSalaryPayment: null,
    savingsRate: 1.5,
    lastInterestPayment: null,
    economyConfig: {
        tva_tax: 0,
        driver_stage_price: 0,
        driver_license_price: 0,
        create_item_ent_tax: 0
    },
    isLoggingIn: false,
    isPanelLoading: false, 
    _completingDrugBatch: false,
    advisorMode: 'moderate',
    activeGovTab: 'dashboard',
    notifications: [],
    characters: [],
    activeCharacter: null, 
    editingCharacter: null, 
    pendingApplications: [],
    allCharactersAdmin: [],
    staffMembers: [], 
    onDutyStaff: [], 
    lawyers: [],
    discordStatuses: {},
    activeGameSession: null,
    sessionHistory: [],
    landingStaff: [],
    landingStats: {},
    serverStats: {
        totalMoney: 0, totalCash: 0, totalBank: 0, totalCoke: 0, totalWeed: 0, heistWinRate: 100
    },
    globalTransactions: [],
    dailyEconomyStats: [],
    pendingHeistReviews: [], 
    erlcData: {
        players: [], queue: [], maxPlayers: 42, currentPlayers: 0, joinKey: '?????', bans: [], modCalls: [], vehicles: [], killLogs: [], commandLogs: [] 
    },
    emergencyCalls: [], 
    policeReports: [], 
    staffSearchQuery: '', 
    staffPermissionSearchResults: [], 
    activePermissionUserId: null, 
    adminDbSort: { field: 'name', direction: 'asc' }, 
    erlcLogSearch: '', 
    vehicleSearchQuery: '', 
    activeStaffLogTab: 'commands',
    gangCreation: { leaderQuery: '', coLeaderQuery: '', leaderResult: null, coLeaderResult: null, searchResults: [], draftName: '' },
    editingGang: null, 
    enterpriseCreation: { draftName: '', leaderQuery: '', coLeaderQuery: '', leaderResult: null, coLeaderResult: null, searchResults: [] },
    editingEnterprise: null,
    ui: { modal: { isOpen: false, type: null, data: null }, toasts: [], sidebarOpen: false, sidebarCollapsedSections: [] },
    economyModal: { isOpen: false, targetId: null, targetName: null, transactions: [] },
    inventoryModal: { isOpen: false, targetId: null, targetName: null, items: [] },
    bankAccount: null,
    transactions: [],
    recipientList: [], 
    filteredRecipients: [], 
    selectedRecipient: null,
    activeBankTab: 'overview', 
    inventory: [],
    patrimonyTotal: 0,
    inventoryFilter: '', 
    idCardModalOpen: false, 
    activeDocumentType: 'id_card',
    idCardTarget: null,
    activeAssetsTab: 'overview', 
    invoices: [],
    activeIllicitTab: 'dashboard', 
    activeHeistLobby: null, 
    heistMembers: [], 
    availableHeistLobbies: [], 
    blackMarketSearch: '', 
    drugLab: null, 
    gangs: [], 
    activeGang: null, 
    bounties: [],
    bountySearchQuery: '',
    bountyTarget: null,
    bountyWinnerSearch: { query: '', results: [], selected: null, bountyId: null },
    activeEnterpriseTab: 'market',
    activeEnterpriseManageTab: 'dashboard',
    enterprises: [],
    myEnterprises: [],
    enterpriseMarket: [],
    topSellers: [],
    pendingEnterpriseItems: [],
    activeEnterpriseManagement: null,
    marketEnterpriseFilter: 'all',
    clientAppointments: [],
    iconPickerOpen: false,
    selectedCreateIcon: 'package',
    iconSearchQuery: '',
    activeServicesTab: 'directory', 
    filteredStreets: [], 
    servicesSearchQuery: '', 
    reportsSearchQuery: '', 
    reportSuspects: [],
    editingReport: null, 
    criminalRecordTarget: null, 
    criminalRecordReports: [],
    policeSearchTarget: null,
    dossierTarget: null, 
    globalActiveHeists: [], 
    currentView: 'login', 
    activeHubPanel: 'main', 
    activeStaffTab: 'citizens', 
    activeEconomySubTab: 'players', 
    alignmentModalShown: false, 
    supabase: null,
    queueCount: 0,
    
    // SANCTIONS STATE
    userSanctions: [],
    activeSanctionTarget: null,
    staffSanctionSearchQuery: '',
    staffSanctionResults: []
};